### PR TITLE
`dot` and `dotc`: kokkos impl

### PR DESCRIPTION
**Pull request by fnrizzi**
#162  is a prerequisite for this, I can rebase once that is merged

### CODE REVIEW

**Comment by mhoemmen** [comment]
Please see my comments on #151; thanks!

**Comment by mhoemmen** [comment]
I've approved and merged PR #151 -- thanks!

**Comment by fnrizzi** [comment]
@mhoemmen i believe this is ready

**Review by mhoemmen — APPROVED** [review]
Looks great!  Thanks for the contribution and for your responses to feedback!

**Pull request merged**
