### PR TITLE
Modify abs_sum to match reference implementation

### LINKED ISSUE #20: BLAS 1: Add vector_abs_sum functions

### PR DESCRIPTION
**Pull request by amklinv-nnl**
Also gave it a test.

Closes #20.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@amklinv-nnl Wow, I did vaguely recall that the reference BLAS implementation unrolled loops by hand, but 6 is such an oddly specific number.  Anyway, this PR is perfectly fine (thanks also for the test! : - D ), but please don't feel like you need to match the reference BLAS implementation at all.  All we need to do is match the latest revision of P1673.

**Comment by mhoemmen** [comment]
@amklinv-nnl The PR tester reports the following error:
```
 CMake Error at CMakeLists.txt:93 (find_package):
-- Configuring incomplete, errors occurred!
See also "/home/runner/work/stdBLAS/stdBLAS/build-mdarray/CMakeFiles/CMakeOutput.log".
  By not providing "FindMDSpan.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MDSpan", but
  CMake did not find one.

  Could not find a package configuration file provided by "MDSpan" with any
  of the following names:

    MDSpanConfig.cmake
    mdspan-config.cmake

  Add the installation prefix of "MDSpan" to CMAKE_PREFIX_PATH or set
  "MDSpan_DIR" to a directory containing one of the above files.  If "MDSpan"
  provides a separate development package or SDK, be sure it has been
  installed.
```
This seems unrelated, but new.  I'm not worried about this for your changes, so just let me know if you would like me to merge this PR now.  Thanks! : - )

**Comment by amklinv-nnl** [comment]
> @amklinv-nnl Wow, I did vaguely recall that the reference BLAS implementation unrolled loops by hand, but 6 is such an oddly specific number. Anyway, this PR is perfectly fine (thanks also for the test! : - D ), but please don't feel like you need to match the reference BLAS implementation at all. All we need to do is match the latest revision of P1673.

My bad; I misunderstood the issue.

> @amklinv-nnl The PR tester reports the following error:

Somebody made a change to capitalization within MDSpan that caused this. I'm happy to fix it, but I need to know whether MDSpan or mdspan is preferable (i.e. whether I fix it in the mdspan or mdarray repo).

**Comment by mhoemmen** [comment]
@amklinv-nnl wrote:
> but I need to know whether MDSpan or mdspan is preferable (i.e. whether I fix it in the mdspan or mdarray repo).

Thanks for offering to fix this!  We should use whatever the latest version of mdspan uses.  If mdarray is broken, then we should patch it.  It's tempting not to require mdarray any more, since P1673R3 no longer refers to it.  (We removed all the mdarray overloads.)  I think the only reason we might still need mdarray is for the tests, so we should feel free to patch mdarray as needed to make those work.

**Comment by amklinv-nnl** [comment]
I just added abs_sum tests, having forgotten this PR existed. d'oh.

**Pull request closed without merging**
